import os
import streamlit.components.v1 as components


PROD = False

if not PROD:
    component = components.declare_component("threeDTilerendererJS", url="http://localhost:3001")
else:
    parent_dir = os.path.dirname(os.path.abspath(__file__))
    build_dir = os.path.join(parent_dir, "frontend-react/build")
    _component_func = components.declare_component("3Dtilerenderer", path=build_dir)
    




def threeTileRenderer(ipfs_file_uri: str, filename: str ):
    """
    renders the 3DTile generated by the georender docker image.
    
     Parameters
    ----------
    
    ipfs_file_URI: defines the  CID of tile pipeline.json file.
    filename: filanem of the file.
    
    
    """
    tilevalue = _component_func(ipfs_file_uri=ipfs_file_uri, name=filename)
    
    


## below is for purely unit testing (by running the code in isolation).
## the parameters provided can 
    if not PROD:
        st.subheader("rendering component")
        ipfs_file = ""
        filename = "pipeline_test"
        
        threeTileRenderer(ipfs_file_uri=ipfs_file, filename=filename)
        
        
        
        

    
    