import os
import streamlit.components.v1 as components
import streamlit as st


class inputparam:
    ipfs_cid_param: str
    tileset_name: str
    


PROD = False 
if PROD:
    _tile_component = components.declare_component(name="TilerendererJS",url="http://localhost:3001")
else:
    parent_dir = os.path.dirname(os.path.abspath(__file__))
    build_dir = os.path.join(parent_dir, "./frontend/build/")
    _tile_component = components.declare_component("3Dtilerenderer", path=build_dir)
    
def threeTileRenderer(ipfs_file_uri: str, filename: str ):
    """
    renders the 3DTile generated by the georender docker image.
    
     Parameters
    ----------
    
    ipfs_file_URI: defines the  CID of tile pipeline.json file.
    filename: filename of the file stored in corresponding URI.
    
    
    """
    ## by default values for testing 
    ipfs_file = "bafybeieoxxdf73ptkw3uqgx225fxpacc6gxdmvb3t5hggtnjmro72e3wl4"
    filename = "pipeline_gen"    

    
    threedcomponent = _tile_component(ipfs_file,filename)

## below is for purely unit testing (by running the code in isolation).
## the parameters provided can 
    st.subheader("rendering component")
    
    return threedcomponent
    
    

threeTileRenderer(ipfs_file_uri=ipfs_file, filename=filename)
        
        
        
        

    
    