version: "3.9"
services:
  georender_build:
    build: 
      context: .
      dockerfile: Dockerfile.georender
    volumes:
      - ../georender/:/usr/src/app/georender/
    ports:
      - "8000:8001"