version: "3.9"
services:
  georender_build:
    build: 
      context: .
      dockerfile: Dockerfile.georender
    volumes:
      - type: bind
        source: ../georender/
        target: /usr/src/app/georender/

    ports:
      - "8000:8001"

  migration:
    build:
      context: ./utils
      dockerfile: Dockerfile.migrateFiles
    volumes:
      - type: bind
        source: ./utils/
        target: /usr/src/app/migration/
    
