version: "3.9"
services:
  georender :
    build: 
      context: .
      dockerfile: Dockerfile-pdal
    image: lxet/lidar_geocoordinate:0.1
    volumes:
      - ../data:/usr/src/app/data

  
  bacalhau:
    build: 
      context: .
      dockerfile: Dockerfile.bacalhau
    image: lxet/bacalau:0.1