name: test of all modules

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize]
    
jobs: 
    build_test:
        name: Build and Test
        runs-on: ubuntu-latest
   
        steps:
          - name: Check out code
            uses: actions/checkout@v3            

          - name: Setting up the npm env
            uses: actions/setup-node@v3
            with:
              node-version: 18
              cache: 'npm'

          - name: cli dependencies build successfully. 
            run: npm run build:cli 

         
        